name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
  
    - name: Set commit status
      if: ${{ github.event.inputs.commit }}
      uses: cmnawagamuwa/TestMainRepo@master
      with:
          # create personal GitHub token to be able to
          # set status in other repositories
          # https://github.com/settings/tokens/new
        authToken: ${{secrets.PAT_TOKEN}
        context: 'Regression tests'
        description: 'Cypress ran the tests'
          # state can be success, error, failure, or pending
          # let's grab it from the Cypress step outcomes
          # https://github.com/cypress-io/github-action#outputs
        state: "test"
        owner: 'cmnawagamuwa'
        repository: 'TestMainRepo'
        sha: ${{github.event.inputs.commit}}
        target_url: "abc"
