name: main

on:
  push:
  #workflow_dispatch:
    #inputs:
      #comment_url:
        #required: true
        #type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Regression Test Report
        path: "**/test-results.trx"                            
        reporter: dotnet-trx     
        fail-on-error: true       
