name: main

on:
  push:
  #workflow_dispatch:
    #inputs:
      #comment_url:
        #required: true
        #type: string
env:
  username: "${{github.actor}}"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: test curl
      run: curl -u user:11fa578250a0669701d9a2b66354a2c441 -X POST https://ci.clare.ai/job/DEV-CHATHURA-Inbox-BUILD-DEPLOY-102914/build?token=remote_build&BUILD_BRANCH=WATI-5600-regression-test-automation-using-Selenium    
      
    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration Release

    - name: Execute Regression Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Generate Regression Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Regression Test Report
        path: "**/test-results.trx"                            
        reporter: dotnet-trx     
        fail-on-error: true       
